name: Build and Publish Docker Image

# 触发条件：当推送到main分支或创建release时
on:
  push:
    tags:
      - 'v*.*.*'

# 环境变量
env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}

jobs:
  build-and-push-image:
    runs-on: ubuntu-latest
    
    # 设置权限
    permissions:
      contents: read
      packages: write
      attestations: write
      id-token: write
    
    steps:
      # 检出代码
      - name: Checkout repository
        uses: actions/checkout@v4
      
      # 登录到GitHub Container Registry
      - name: Log in to Container Registry
        uses: docker/login-action@v3
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      
      # 提取Docker镜像的标签和标签信息
      - name: Extract metadata for Docker
        id: meta
        run: |
          echo "DOCKER_TAGS=ghcr.io/${REPO_LC}:dev" >> $GITHUB_ENV
      
      # 构建并推送Docker镜像
      - name: Build and push Docker image
        id: push
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
      
 
